import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';
import Toast from 'react-bootstrap/Toast';
import { useState } from "react";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {

  const [klicked, isKlicked] = useState(false);
  const [message, sendMessage] = useState(" ");

  const router = useRouter();

  const nextSeite = () => {
    router.push("/geschenk")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-success m-3 p-1 rounded-1" style={{ height: '100%' }}>

        <h5 className="text-danger text-center">Hallo Schatz willkommen auf deiner Website</h5>
        <p className="text-center text-danger">Dies sind deine Gutscheine für deinen heutigen Geburtstag diese kannst du nur innerhalb der nächsten 48h einlösen, vergiss das nicht ;o</p>
        <div style={{ height: '100%' }}>
          <Card className="bg-primary text-white rounded-3 shadow-lg m-1" style={{ width: '100%', maxWidth: '350px' }}>
            <Card.Img
              variant="top"
              src="bilder/massage.jpg"
              className="rounded-top"
              style={{ height: '200px', objectFit: 'cover' }}
            />
            <Card.Body className="d-flex flex-column align-items-center">
              <Card.Title className="mb-3 text-center fs-4 fw-bold">15 Minuten Massage</Card.Title>
              <Button variant="success" className="px-4 py-2 fw-semibold" onClick={() => {
                sendMessage("15 Minuten Massage");
                isKlicked(true);
              }}>
                Drück mich
              </Button>
            </Card.Body>
          </Card>


          <Card className="bg-primary text-white rounded-3 shadow-lg m-1" style={{ width: '100%', maxWidth: '350px' }}>
            <Card.Img
              variant="top"
              src="bilder/streicheln.jpg"
              className="rounded-top"
              style={{ height: '200px', objectFit: 'cover' }}
            />
            <Card.Body className="d-flex flex-column align-items-center">
              <Card.Title className="mb-3 text-center fs-4 fw-bold">15 Minuten streicheln</Card.Title>
              <Button variant="success" className="px-4 py-2 fw-semibold" onClick={() => {
                sendMessage("15 Minuten streicheln");
                isKlicked(true);
              }}>
                Drück mich
              </Button>
            </Card.Body>
          </Card>

          <Card className="bg-primary text-white rounded-3 shadow-lg m-1" style={{ width: '100%', maxWidth: '350px' }}>
            <Card.Img
              variant="top"
              src="bilder/filme.jpg"
              className="rounded-top"
              style={{ height: '200px', objectFit: 'cover' }}
            />
            <Card.Body className="d-flex flex-column align-items-center">
              <Card.Title className="mb-3 text-center fs-4 fw-bold">1 Film deiner Wahl</Card.Title>
              <Button variant="success" className="px-4 py-2 fw-semibold" onClick={() => {
                sendMessage("1 Film deiner Wahl");
                isKlicked(true);
              }}>
                Drück mich
              </Button>
            </Card.Body>
          </Card>
        </div>
      </div>

      <div className="d-flex justify-content-center mb-1 mt-1">
        <Button variant="success" className="px-4 py-2 fw-semibold" onClick={() => nextSeite()}>
          <p className="mb-0"><b>Fuchsbau</b></p> (erst drücken wenn mit Frühstück fertig!)
        </Button>
      </div>

      <div>
        {klicked ? (

          <Toast className="fixed-top w-100">
            <Toast.Header>
              <img src="holder.js/20x20?text=%20" className="rounded me-2" alt="" />
              <strong className="me-auto">Buchung</strong>
              <small>11 mins ago</small>
            </Toast.Header>
            <Toast.Body>Du hast {message} gebucht!</Toast.Body>
          </Toast>
        ) : (
          ""
        )}
      </div>
      <div className="bg-danger mt-2">
        <h2>PS: Ich Liebe dich</h2>
      </div>
    </>
  );
}
